### ISSUE TITLE
Fix Contributors Section 

### ISSUE THREAD

**Issue by dennypradipta** [dennypradipta/mern-with-jwt#15]
Fairly easy task, please fix the README in Contributors section because unfortunately Github cannot display HTML well. I just want a table that contains avatar, name and github profile link.

Please comment first if you want to take this issue, then do Pull Request.

Thanks

**Comment by dennypradipta** [comment]
A reference for the table: https://github.com/jaredpalmer/formik

**Comment by me-ydv-5** [comment]
Taking up the task.

**Comment by ernestognw** [comment]
I'mt taking this
