### ISSUE TITLE
Connect React Todo App with Database

### ISSUE THREAD

**Issue by dennypradipta** [dennypradipta/mern-with-jwt#3]
As you can see, currently the todo app after you logged in are not connected to the database when you add, edit, delete the task. I need you to connect them. API is in the issue #2 so probably you can wait or just work on both issue.

Thanks

**Comment by dennypradipta** [comment]
The API is up. Contributors now can use API for the Todo

**Comment by imravichhetri** [comment]
@dennypradipta I would like to work on this.

**Comment by imravichhetri** [comment]
#8  Please look into this.

**Comment by dennypradipta** [comment]
Wow. Amazing code! I loved how you implemented the edit task by double clicking it. That is pretty cool!

Also, it's okay if you changed the schema a little bit.

Thank you so much for your contribution!
