### ISSUE TITLE
Add Register Page

### ISSUE THREAD

**Issue by dennypradipta** [dennypradipta/mern-with-jwt#4]
This is fairly an easy task, I want you to add a Register Page below Login Button. Please make it identical with the login page

The fields are Name, Username, and Password. Check out the UserModel I have. For the endpoint, it's /api/user/register

Thanks

**Comment by tlcheah2** [comment]
Hi @dennypradipta , can i take this ?

**Comment by dennypradipta** [comment]
There's someone who applied the register page, but only the wireframe though #5

Maybe you can implement the register page, with working register button. Please check the endpoint for register in backend/routes/user.js

Thanks
