### ISSUE TITLE
Add a checklist when the task is done

### ISSUE THREAD

**Issue by dennypradipta** [dennypradipta/mern-with-jwt#9]
On the left side of the task name, provide a checkbox. 

When the checkbox is checked, apply strikethrough to the task name. And do API call to mark the task as done.

Of course, you will need to change some line of code in the TodoModel. You need to add one field called "status" or "done" as a Boolean, and fields for timestamps when the task is done. You can use Date.js or Moment Timezone. It's up to you.

Also, you will need to create an API endpoint in backend/routes/todo.js to patch task status.

Happy hacking!

**Comment by ashwinimanoj** [comment]
Hi @dennypradipta , can I work on this issue?

**Comment by dennypradipta** [comment]
Of course. Do your best!

**Comment by ashwinimanoj** [comment]
Thanks! I am unable to login/register when I run the frontend and backend. I see a 401 error, and clicking on Register does not take me to the Registration page. Is there something more I should be doing?

**Comment by dennypradipta** [comment]
Register is not implemented yet I think. Perhaps you could do it as well? I opened an issue for it though, but no progress after the skeleton was made.

Current workaround is that you can use Postman to register yourself. Check out the route for register in backend/routes/users.js. There you will know what to put in request body

**Comment by ashwinimanoj** [comment]
Okay sure! Thanks, I will pick this up first.

**Comment by dennypradipta** [comment]
Sure. Please refer to this issue in the PR description after you're done. I am going to sleep, it's 12AM right now in Indonesia.

**Comment by ashwinimanoj** [comment]
Okay, sure will do! Thanks for the help! 10:43 PM now in India. Good night.

**Comment by ashwinimanoj** [comment]
When you say timestamp, do you mean the last modified time or only the time that the todo was modified? If it's latter, then what should happen the todo is unchecked, should I remove this field in that case?

**Comment by dennypradipta** [comment]
My concept is when the task is marked as done, it will add a field such as "done_at" with timestamps. If unmarked as not done, it will removed the done_at field. 

But yeah, I think it's out of the scope. Let's just focus on basic functionality first. I'll open up new issue for the timestamps

**Comment by ashwinimanoj** [comment]
Ah, would 'last modified time' be a good alternative to 'done at'? I am done with the basic functionality, will create a PR now.

**Comment by dennypradipta** [comment]
Alright, it's looking pretty good. Time to close this issue then

Thank you
